/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from 'ethers';
import type { FunctionFragment, Result } from '@ethersproject/abi';
import type { Listener, Provider } from '@ethersproject/providers';
import type { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from '../../../common';

export interface PoolStorageV1_7Interface extends utils.Interface {
  functions: {
    'minimumTCLSeedingThreshold()': FunctionFragment;
  };

  getFunction(nameOrSignatureOrTopic: 'minimumTCLSeedingThreshold'): FunctionFragment;

  encodeFunctionData(functionFragment: 'minimumTCLSeedingThreshold', values?: undefined): string;

  decodeFunctionResult(functionFragment: 'minimumTCLSeedingThreshold', data: BytesLike): Result;

  events: {};
}

export interface PoolStorageV1_7 extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: PoolStorageV1_7Interface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(eventFilter: TypedEventFilter<TEvent>): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    minimumTCLSeedingThreshold(overrides?: CallOverrides): Promise<[BigNumber]>;
  };

  minimumTCLSeedingThreshold(overrides?: CallOverrides): Promise<BigNumber>;

  callStatic: {
    minimumTCLSeedingThreshold(overrides?: CallOverrides): Promise<BigNumber>;
  };

  filters: {};

  estimateGas: {
    minimumTCLSeedingThreshold(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    minimumTCLSeedingThreshold(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
