/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from 'ethers';
import type { FunctionFragment, Result } from '@ethersproject/abi';
import type { Listener, Provider } from '@ethersproject/providers';
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from '../../../common';

export interface IToucanPoolTestInterface extends utils.Interface {
  functions: {
    'feeRedeemPercentageInBase()': FunctionFragment;
    'getScoredTCO2s()': FunctionFragment;
    'redeemAndRetireMany(address[],uint256[])': FunctionFragment;
    'redeemAuto(uint256)': FunctionFragment;
    'redeemAuto2(uint256)': FunctionFragment;
    'redeemMany(address[],uint256[])': FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | 'feeRedeemPercentageInBase'
      | 'getScoredTCO2s'
      | 'redeemAndRetireMany'
      | 'redeemAuto'
      | 'redeemAuto2'
      | 'redeemMany'
  ): FunctionFragment;

  encodeFunctionData(functionFragment: 'feeRedeemPercentageInBase', values?: undefined): string;
  encodeFunctionData(functionFragment: 'getScoredTCO2s', values?: undefined): string;
  encodeFunctionData(
    functionFragment: 'redeemAndRetireMany',
    values: [PromiseOrValue<string>[], PromiseOrValue<BigNumberish>[]]
  ): string;
  encodeFunctionData(
    functionFragment: 'redeemAuto',
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: 'redeemAuto2',
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: 'redeemMany',
    values: [PromiseOrValue<string>[], PromiseOrValue<BigNumberish>[]]
  ): string;

  decodeFunctionResult(functionFragment: 'feeRedeemPercentageInBase', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'getScoredTCO2s', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'redeemAndRetireMany', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'redeemAuto', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'redeemAuto2', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'redeemMany', data: BytesLike): Result;

  events: {};
}

export interface IToucanPoolTest extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IToucanPoolTestInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(eventFilter: TypedEventFilter<TEvent>): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    feeRedeemPercentageInBase(overrides?: CallOverrides): Promise<[BigNumber]>;

    getScoredTCO2s(overrides?: CallOverrides): Promise<[string[]]>;

    redeemAndRetireMany(
      tco2s: PromiseOrValue<string>[],
      amounts: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    redeemAuto(
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    redeemAuto2(
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    redeemMany(
      tco2s: PromiseOrValue<string>[],
      amounts: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  feeRedeemPercentageInBase(overrides?: CallOverrides): Promise<BigNumber>;

  getScoredTCO2s(overrides?: CallOverrides): Promise<string[]>;

  redeemAndRetireMany(
    tco2s: PromiseOrValue<string>[],
    amounts: PromiseOrValue<BigNumberish>[],
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  redeemAuto(
    amount: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  redeemAuto2(
    amount: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  redeemMany(
    tco2s: PromiseOrValue<string>[],
    amounts: PromiseOrValue<BigNumberish>[],
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    feeRedeemPercentageInBase(overrides?: CallOverrides): Promise<BigNumber>;

    getScoredTCO2s(overrides?: CallOverrides): Promise<string[]>;

    redeemAndRetireMany(
      tco2s: PromiseOrValue<string>[],
      amounts: PromiseOrValue<BigNumberish>[],
      overrides?: CallOverrides
    ): Promise<
      [BigNumber[], BigNumber[]] & { retirementIds: BigNumber[]; redeemedAmounts: BigNumber[] }
    >;

    redeemAuto(amount: PromiseOrValue<BigNumberish>, overrides?: CallOverrides): Promise<void>;

    redeemAuto2(
      amount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string[], BigNumber[]]>;

    redeemMany(
      tco2s: PromiseOrValue<string>[],
      amounts: PromiseOrValue<BigNumberish>[],
      overrides?: CallOverrides
    ): Promise<BigNumber[]>;
  };

  filters: {};

  estimateGas: {
    feeRedeemPercentageInBase(overrides?: CallOverrides): Promise<BigNumber>;

    getScoredTCO2s(overrides?: CallOverrides): Promise<BigNumber>;

    redeemAndRetireMany(
      tco2s: PromiseOrValue<string>[],
      amounts: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    redeemAuto(
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    redeemAuto2(
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    redeemMany(
      tco2s: PromiseOrValue<string>[],
      amounts: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    feeRedeemPercentageInBase(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getScoredTCO2s(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    redeemAndRetireMany(
      tco2s: PromiseOrValue<string>[],
      amounts: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    redeemAuto(
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    redeemAuto2(
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    redeemMany(
      tco2s: PromiseOrValue<string>[],
      amounts: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
