/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface IToucanContractRegistryInterface extends ethers.utils.Interface {
  functions: {
    "carbonOffsetBadgesAddress()": FunctionFragment;
    "carbonOffsetBatchesAddress()": FunctionFragment;
    "carbonProjectVintagesAddress()": FunctionFragment;
    "carbonProjectsAddress()": FunctionFragment;
    "checkERC20(address)": FunctionFragment;
    "toucanCarbonOffsetsFactoryAddress()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "carbonOffsetBadgesAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "carbonOffsetBatchesAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "carbonProjectVintagesAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "carbonProjectsAddress",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "checkERC20", values: [string]): string;
  encodeFunctionData(
    functionFragment: "toucanCarbonOffsetsFactoryAddress",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "carbonOffsetBadgesAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "carbonOffsetBatchesAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "carbonProjectVintagesAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "carbonProjectsAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "checkERC20", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "toucanCarbonOffsetsFactoryAddress",
    data: BytesLike
  ): Result;

  events: {};
}

export class IToucanContractRegistry extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: IToucanContractRegistryInterface;

  functions: {
    carbonOffsetBadgesAddress(overrides?: CallOverrides): Promise<[string]>;

    carbonOffsetBatchesAddress(overrides?: CallOverrides): Promise<[string]>;

    carbonProjectVintagesAddress(overrides?: CallOverrides): Promise<[string]>;

    carbonProjectsAddress(overrides?: CallOverrides): Promise<[string]>;

    checkERC20(_address: string, overrides?: CallOverrides): Promise<[boolean]>;

    toucanCarbonOffsetsFactoryAddress(
      overrides?: CallOverrides
    ): Promise<[string]>;
  };

  carbonOffsetBadgesAddress(overrides?: CallOverrides): Promise<string>;

  carbonOffsetBatchesAddress(overrides?: CallOverrides): Promise<string>;

  carbonProjectVintagesAddress(overrides?: CallOverrides): Promise<string>;

  carbonProjectsAddress(overrides?: CallOverrides): Promise<string>;

  checkERC20(_address: string, overrides?: CallOverrides): Promise<boolean>;

  toucanCarbonOffsetsFactoryAddress(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    carbonOffsetBadgesAddress(overrides?: CallOverrides): Promise<string>;

    carbonOffsetBatchesAddress(overrides?: CallOverrides): Promise<string>;

    carbonProjectVintagesAddress(overrides?: CallOverrides): Promise<string>;

    carbonProjectsAddress(overrides?: CallOverrides): Promise<string>;

    checkERC20(_address: string, overrides?: CallOverrides): Promise<boolean>;

    toucanCarbonOffsetsFactoryAddress(
      overrides?: CallOverrides
    ): Promise<string>;
  };

  filters: {};

  estimateGas: {
    carbonOffsetBadgesAddress(overrides?: CallOverrides): Promise<BigNumber>;

    carbonOffsetBatchesAddress(overrides?: CallOverrides): Promise<BigNumber>;

    carbonProjectVintagesAddress(overrides?: CallOverrides): Promise<BigNumber>;

    carbonProjectsAddress(overrides?: CallOverrides): Promise<BigNumber>;

    checkERC20(_address: string, overrides?: CallOverrides): Promise<BigNumber>;

    toucanCarbonOffsetsFactoryAddress(
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    carbonOffsetBadgesAddress(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    carbonOffsetBatchesAddress(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    carbonProjectVintagesAddress(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    carbonProjectsAddress(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    checkERC20(
      _address: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    toucanCarbonOffsetsFactoryAddress(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
