/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as iInterchainSecurityModuleSol from './IInterchainSecurityModule.sol';
export type { iInterchainSecurityModuleSol };
import type * as hooks from './hooks';
export type { hooks };
export type { IMailbox } from './IMailbox';
export type { IMessageRecipient } from './IMessageRecipient';
