/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IDIMOCostBasisSales__factory } from './IDIMOCostBasisSales__factory';
export { IDIMOUserProfile__factory } from './IDIMOUserProfile__factory';
