/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from 'ethers';
import type { Provider } from '@ethersproject/providers';
import type {
  ToucanContractRegistryStorage,
  ToucanContractRegistryStorageInterface,
} from '../../../contracts/ToucanContractRegistryStorage.sol/ToucanContractRegistryStorage';

const _abi = [
  {
    inputs: [
      {
        internalType: 'string',
        name: '',
        type: 'string',
      },
    ],
    name: 'toucanCarbonOffsetFactories',
    outputs: [
      {
        internalType: 'address',
        name: '',
        type: 'address',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
] as const;

export class ToucanContractRegistryStorage__factory {
  static readonly abi = _abi;
  static createInterface(): ToucanContractRegistryStorageInterface {
    return new utils.Interface(_abi) as ToucanContractRegistryStorageInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ToucanContractRegistryStorage {
    return new Contract(address, _abi, signerOrProvider) as ToucanContractRegistryStorage;
  }
}
