/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { CarbonOffsetBatchesStorage } from './CarbonOffsetBatchesStorage';
export type { CarbonOffsetBatchesStorageV1 } from './CarbonOffsetBatchesStorageV1';
