/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as retirementCertificatesStorageSol from './RetirementCertificatesStorage.sol';
export type { retirementCertificatesStorageSol };
import type * as dimo from './dimo';
export type { dimo };
import type * as interfaces from './interfaces';
export type { interfaces };
export type { RetirementCertificateFractionalizer } from './RetirementCertificateFractionalizer';
export type { RetirementCertificateFractionalizerStorage } from './RetirementCertificateFractionalizerStorage';
export type { RetirementCertificateFractions } from './RetirementCertificateFractions';
export type { RetirementCertificateFractionsStorage } from './RetirementCertificateFractionsStorage';
export type { RetirementCertificates } from './RetirementCertificates';
