/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ToucanCrosschainMessengerStorage__factory } from './ToucanCrosschainMessengerStorage__factory';
export { ToucanCrosschainMessengerStorageV1__factory } from './ToucanCrosschainMessengerStorageV1__factory';
